"""Lexical selection: task -> tokens -> scored, ranked ContextItems.

This is the first cut at SELECT. It has no notion of imports or transitive
reach (that is step 5) -- it scores each discovered file against the task's
tokens using filename hits, Python symbol-definition hits, and damped
content frequency, then keeps the files that score above a threshold, up to
a cap.
"""

from __future__ import annotations

import ast
import math
import re
from pathlib import PurePosixPath

from .context import ContextItem, Excerpt
from .discovery import DATA_DIR_SEGMENTS, DiscoveredFile

# --------------------------------------------------------------------------
# Tunable constants. Everything a future tuning pass (step 11) might touch
# lives in this block so it can be adjusted in one place.
# --------------------------------------------------------------------------

# --- bug fix: threshold too permissive ---
# Below this bar, a bare score > 0.0 admitted a single incidental content
# mention (e.g. "user experience" in a marketing bio, matched only once,
# with no filename/symbol signal and no role bonus) as if it were a real
# result. Observed on a real Next.js/TypeScript repo with no login/session
# code at all: such incidental mentions scored ~1.4, while every genuine
# signal in the auth_bug fixture (filename hit, symbol hit, or a single
# config/doc/test mention plus its ROLE_BONUS) scores comfortably above 2.0.
# Raising the threshold to 2.0 means a bare, role-bonus-less, single
# content mention no longer clears the bar on its own -- consistent with
# the plan's "no relevant context found" being a correct, valuable answer
# rather than something to avoid.
SCORE_THRESHOLD = 2.0
MAX_SEEDS = 12

WEIGHT_FILENAME = 10.0
WEIGHT_SYMBOL = 6.0
CONTENT_CAP = 6.0
CONTENT_MULT = 2.0
ROLE_BONUS = 2.0
ROLE_BONUS_ROLES = {"config", "docs", "test"}

MIN_TOKEN_LEN = 3

# --- real-repo tuning (step 11) ---
# Observed on a data-heavy real repo (~/Dali): a 700KB benchmark-results
# JSON outranked the source file that actually implements the task, purely
# on repeated-content volume. Two independent, narrowly-scoped penalties
# address this without touching the filename or symbol-definition signals
# (the strongest, most trustworthy evidence of relevance regardless of
# file size or location):
#   - LARGE_FILE_CONTENT_PENALTY damps only the content-frequency
#     component for files over LARGE_FILE_BYTES, since a big file
#     mentioning a term hundreds of times is not hundreds of times more
#     relevant than a small file mentioning it once.
#   - DATA_PATH_PENALTY damps the *whole* score for files under a
#     recognizable data/vendor/build directory (see discovery.DATA_DIR_SEGMENTS),
#     since bulk data and vendored/generated output are not the files a
#     developer wants surfaced first even when they happen to score well.
# Generated files (marked as such in their own header) get the same
# treatment for the same reason.
LARGE_FILE_BYTES = 50_000
LARGE_FILE_CONTENT_PENALTY = 0.3

DATA_PATH_PENALTY = 0.25

_GENERATED_MARKERS = (
    "do not edit", "do not modify", "autogenerated", "auto-generated",
    "@generated", "generated by",
)
GENERATED_FILE_PENALTY = 0.15
_GENERATED_SNIFF_CHARS = 4096

# --- transitive import expansion (step 5) ---
# First-party Python import graph, walked in both directions from the seed
# set: files a seed imports, and files that import a seed. Bounded by
# MAX_DEPTH hops, MAX_EXPANDED files total, and per-hop score decay so
# distant, weakly-connected files do not crowd out direct matches.
MAX_DEPTH = 2
IMPORT_DECAY = 0.5
MAX_EXPANDED = 8
# Tuned down from an earlier 40 after step-11 evaluation against a real
# repo (~/Dali): with a permissive cap and SCORE_THRESHOLD = 0.0, a single
# task pulled in 39 files and an 800+ line rendering -- technically all
# above-threshold, but well past what a developer will actually read.
# MAX_SEEDS/MAX_EXPANDED/MAX_INCLUDED together now bound a run to roughly
# the files worth opening first, not everything that scored above zero.
MAX_INCLUDED = 18

# --- bounded excerpt extraction + redaction (step 6) ---
# Excerpts are the spans that justified an item's inclusion, not whole
# files: matched symbol definitions, matched config/doc/content lines, and
# -- for import-reached files -- the specific definitions the importing
# file actually imported. Three bounds keep this a budget rather than a
# second copy of the repo: a per-span line cap, a per-file excerpt-count
# cap, and a package-wide byte cap. Overlapping/adjacent spans are merged
# before any cap is applied. When the package-wide budget is exceeded,
# whole excerpts are dropped lowest-item-score-first and the drop count is
# recorded in trace["excerpts_dropped_over_budget"].
MAX_EXCERPT_LINES = 40
MAX_EXCERPTS_PER_FILE = 3
MAX_PACKAGE_BYTES = 60_000

# --- bug fix: excerpt bounds are line-based only ---
# MAX_EXCERPT_LINES does nothing against a minified file that is a single
# multi-thousand-character line: one "line" can still blow the whole
# package byte budget by itself. MAX_EXCERPT_CHARS caps a single excerpt's
# *text* length directly, independent of how many lines it spans, and is
# comfortably below MAX_PACKAGE_BYTES so no one excerpt can ever exhaust
# the package budget on its own. Over-long text is truncated with a clear
# trailing marker rather than silently cut off mid-content.
MAX_EXCERPT_CHARS = 2_000
TRUNCATION_MARKER = " …[truncated]"

# --- bug fix: minified/generated assets scanned as prose ---
# Content-frequency matching over a minified/generated asset produces
# coincidental "hits" that have nothing to do with the task -- e.g. the SVG
# keyword `userSpaceOnUse` containing "user" as a raw substring. Path and
# filename matching still applies (a file literally named after a task
# term is still relevant); only the content-frequency scoring component
# and fallback content excerpting are skipped for files classified as an
# asset. Kept as a small, comprehensible rule set rather than an
# exhaustive list, per the plan.
ASSET_EXTENSIONS = {".svg", ".map"}
ASSET_FILENAME_SUFFIXES = (".min.js", ".min.css")
ASSET_LOCKFILE_NAMES = {
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "composer.lock",
    "gemfile.lock", "cargo.lock", "poetry.lock", "pipfile.lock",
}
ASSET_DIR_SEGMENTS = {"public", "dist", "build", "vendor"}
# A very high average line length is a strong minification signal --
# hand-written prose and source rarely average anywhere near this many
# characters per line, while minified/bundled output routinely does.
ASSET_AVG_LINE_LENGTH = 500

# Span weights used only to rank *which* spans survive the per-file and
# package-wide caps -- not exposed on the item itself.
#
# Priority order (step 7): symbol definitions > config key lines > doc
# headings/assertions > everything else. The "everything else" tier
# (WEIGHT_MATCHED_LINE, bare content-frequency lines) is only used as a
# fallback when a file has no spans in any higher tier -- see
# attach_excerpts(). This is what keeps prose/docstring sentences out of
# files that already have a structural match.
WEIGHT_IMPORTED_SYMBOL = 100.0
WEIGHT_MATCHED_SYMBOL = 50.0
WEIGHT_CONFIG_KEY = 40.0
WEIGHT_DOC_ASSERTION = 30.0
WEIGHT_MATCHED_LINE = 1.0

REDACTED = "«redacted»"

# Key names that look like they hold a secret. Matched as a substring of
# the key (case-insensitive), so "api_key", "apikey", "access_key", and
# "private_key" are all covered by "key" without needing to be spelled out
# individually. Deliberately broad: an over-redacted key name is a minor
# annoyance, a leaked credential is not.
#
# "token" is handled separately, not folded into this substring list: on a
# real repo (step 11) it caught "max_tokens" (an LLM parameter, not a
# secret) because "token" is a substring of "tokens". "access_token" /
# "auth_token" / a bare "TOKEN" env var are real secrets and must still be
# caught -- see _looks_like_secret_key() below, which narrows "token" to
# exclude the token-*count* and tokenizer senses of the word rather than
# dropping it entirely.
_SECRET_KEY_SUBSTRINGS = ("key", "secret", "password", "passwd", "credential")

# Compounds where "token" means a token *count* or the tokenizer concept,
# not a credential -- extremely common in LLM-adjacent code. Matched after
# camelCase/snake_case normalization, so "maxTokens" and "max_tokens" both
# resolve the same way.
_NON_SECRET_TOKEN_RE = re.compile(
    r"(?:max|min|num|total|input|output|completion|prompt|context|budget)s?[_-]?tokens?\b"
    r"|tokens?[_-]?(?:count|limit|budget|length)\b"
    r"|tokeniz"
)

# `KEY = value` / `KEY: value` / `KEY=value`, case-insensitive on the key.
_SECRET_KEY_LINE_RE = re.compile(
    r"^(?P<prefix>\s*[A-Za-z_][A-Za-z0-9_.\-]*)(?P<sep>\s*[:=]\s*)(?P<value>.+)$"
)

# Standalone high-entropy shapes, even outside a `key: value` line. The
# prefixed patterns (sk-..., AKIA...) are specific enough to redact
# unconditionally. The generic 32+-char catch-all is not: a long, all-
# letters snake_case identifier -- e.g. a real test name like
# "test_needs_verification_excluded" (32 chars, observed on a real repo
# during step-11 evaluation) -- matches its character class just as well
# as a real secret does, and unconditionally redacting it silently mangles
# ordinary code with no security benefit. Real secrets are near-universally
# a mix of letters *and* digits (base64/hex/JWT output); requiring at
# least one digit keeps the catch-all as a defense-in-depth net for
# unlabeled secrets without also eating long identifiers that happen to be
# made of dictionary-ish words.
_ENTROPY_PREFIXED_PATTERNS = [
    re.compile(r"\bsk-[A-Za-z0-9_]{10,}\b"),
    re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
]
# No "/" in the generic catch-all's character class: a versioned URL or a
# repo-relative file path (both observed on a real repo during step-11
# evaluation, e.g. "https://dali.yenk.dev/schemas/canonical-citation-v1.json"
# and "data/benchmark/tier1/corpus/citation_failure_cases.json") is a
# multi-segment "/"-joined string that is well over 32 chars and contains
# a digit, so it otherwise passes every other test this pattern applies. A
# real standalone secret is a single contiguous token; it does not need
# "/" to be recognized, and dropping it here removes an entire class of
# false positives on paths and URLs without giving up real coverage.
_ENTROPY_GENERIC_RE = re.compile(r"\b[A-Za-z0-9+_-]{32,}={0,2}\b")


def _redact_generic_entropy(match: re.Match) -> str:
    token = match.group(0)
    return REDACTED if any(c.isdigit() for c in token) else token

STOPWORDS = {
    "fix", "bug", "the", "a", "an", "in", "to", "for", "of", "and",
    "issue", "error", "problem", "add", "update", "make", "when", "with",
    "is", "are", "was", "were", "be", "been", "being", "on", "at", "by",
    "this", "that", "these", "those", "it", "its", "as", "or", "not",
    "please", "need", "needs", "can", "should", "would", "could", "will",
    "file", "files", "code", "does", "doesn", "why", "how", "what",
    "into", "from", "there", "here", "some", "any", "all", "new", "old",
}

# --------------------------------------------------------------------------


def _split_camel_and_snake(text: str) -> str:
    """Insert spaces at camelCase and snake_case boundaries so both split
    into separate tokens on the later non-alnum split.
    """
    # lower/digit -> Upper boundary: "authBug" -> "auth Bug"
    text = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", text)
    # Upper Upper -> Upper lower boundary: "HTTPServer" -> "HTTP Server"
    text = re.sub(r"(?<=[A-Z])(?=[A-Z][a-z])", " ", text)
    return text


def tokenize(task: str) -> list[str]:
    """lowercase, split on non-alphanumerics and camelCase/snake_case
    boundaries, drop stopwords, drop tokens under MIN_TOKEN_LEN chars.
    """
    text = _split_camel_and_snake(task)
    text = text.lower()
    raw_tokens = re.split(r"[^a-z0-9]+", text)
    tokens = [
        t for t in raw_tokens
        if t and len(t) >= MIN_TOKEN_LEN and t not in STOPWORDS
    ]
    return tokens


def _path_segments(path: str) -> list[str]:
    """Path segments (original case preserved -- see _iter_word_matches,
    which needs case to tell a camelCase hump from a bare substring),
    including the filename stem split off from its extension, for
    filename/path-segment matching.
    """
    parts = re.split(r"[\\/]", path)
    segments: list[str] = []
    for part in parts:
        segments.append(part)
        stem = re.sub(r"\.[A-Za-z0-9]+$", "", part)
        if stem and stem != part:
            segments.append(stem)
    return segments


# --------------------------------------------------------------------------
# Bug fix: word-boundary term matching.
#
# Plain substring matching (`term in haystack`) matched "user" inside
# "userSpaceOnUse" (an SVG coordinate-system keyword) and let a single
# incidental "user experience" mention in prose outrank a genuinely
# relevant file. This is bounded matching instead: a term is a real word
# match only when it sits at a real boundary on *both* sides -- either a
# non-identifier character (matching the non-alnum split tokenize() already
# uses for the task side), or a camelCase hump (the same lower-followed-by-
# upper transition _split_camel_and_snake() inserts a space at).
#
# The camelCase side is deliberately one-directional: a hump is only
# accepted as a boundary when the matched text itself starts with an
# uppercase letter (i.e. the match is a properly-capitalized word segment,
# as in "getUser" or "UserSession"). A lowercase term sitting at the front
# of a longer lowerCamelCase identifier with no real delimiter --
# "userSpaceOnUse" is "user" + "Space" + "On" + "Use" by the same splitting
# rule -- does NOT get a free pass just because a capital happens to follow
# it; that leading lowercase run is exactly the ambiguous, false-positive-
# prone shape this fix targets. "user_id" and "UserSession" still match
# because they have (respectively) an explicit delimiter and a
# capitalized, hump-bounded match.
# --------------------------------------------------------------------------


def _iter_word_matches(text: str, term: str):
    """Yield the start indices in `text` where `term` occurs as a genuine
    word -- respecting identifier boundaries (camelCase humps and
    snake_case/other delimiters) rather than as an arbitrary substring.
    Matching is case-insensitive; boundary decisions use the original
    (unlowered) text so a camelCase hump can be detected.
    """
    if not term:
        return
    text_lower = text.lower()
    term_lower = term.lower()
    tlen = len(term_lower)
    n = len(text)
    pos = 0
    while True:
        idx = text_lower.find(term_lower, pos)
        if idx == -1:
            return
        pos = idx + 1
        end = idx + tlen
        matched_is_upper_start = text[idx].isupper()
        before = text[idx - 1] if idx > 0 else ""
        after = text[end] if end < n else ""

        left_ok = (
            idx == 0
            or not before.isalnum()
            or ((before.islower() or before.isdigit()) and matched_is_upper_start)
        )
        if not left_ok:
            continue

        right_ok = end == n or not after.isalnum()
        if not right_ok and matched_is_upper_start and after.isupper():
            right_ok = True

        if right_ok:
            yield idx


def has_word_match(text: str, term: str) -> bool:
    """True if `term` occurs anywhere in `text` as a genuine word."""
    for _ in _iter_word_matches(text, term):
        return True
    return False


def count_word_matches(text: str, term: str) -> int:
    """Count of genuine word occurrences of `term` in `text`."""
    return sum(1 for _ in _iter_word_matches(text, term))


def _is_asset_like(path: str, content: str) -> bool:
    """True when `path`/`content` looks like a minified, generated, or
    vendored asset rather than hand-written prose or source -- see the
    ASSET_* tunables above. Used only to disable content-frequency
    matching and the generic content-line excerpt fallback; path/filename
    matching is unaffected.
    """
    name = PurePosixPath(path).name
    lower_name = name.lower()
    if lower_name in ASSET_LOCKFILE_NAMES:
        return True
    ext = PurePosixPath(lower_name).suffix
    if ext in ASSET_EXTENSIONS:
        return True
    if lower_name.endswith(ASSET_FILENAME_SUFFIXES):
        return True
    dir_parts = path.lower().split("/")[:-1]
    if any(part in ASSET_DIR_SEGMENTS for part in dir_parts):
        return True
    if content:
        lines = content.splitlines() or [content]
        avg_len = sum(len(line) for line in lines) / len(lines)
        if avg_len > ASSET_AVG_LINE_LENGTH:
            return True
    return False


def _build_reason(
    role: str,
    filename_terms: list[str],
    symbol_names: list[str],
    content_term_counts: dict[str, int],
) -> str:
    """Turn the raw signals that made a file score above threshold into a
    short, human sentence fragment -- not a telemetry dump.

    Leads with the strongest signal (matching the score weighting:
    filename > symbol > content), never concatenates multiple signals with
    semicolons, never surfaces a raw score or occurrence count, and never
    emits a bare "matched".
    """
    if filename_terms:
        return f"filename matches '{filename_terms[0]}'"

    if symbol_names:
        return f"defines {symbol_names[0]}"

    if content_term_counts:
        # Strongest content signal: the term mentioned most often.
        term = max(content_term_counts, key=lambda t: content_term_counts[t])
        if role == "docs":
            return f"defines {term} requirements"
        if role == "config":
            return f"configuration referenced by {term} code"
        if role == "test":
            return "tests for affected functionality"
        if role == "source":
            return f"references {term}"
        return f"mentions {term}"

    return "matches task terms"


def _in_data_path(path: str) -> bool:
    """True when `path` is under a recognizable data/vendor/build
    directory (see discovery.DATA_DIR_SEGMENTS) -- used only to apply
    DATA_PATH_PENALTY, never to exclude the file outright.
    """
    dir_parts = path.lower().split("/")[:-1]
    return any(part in DATA_DIR_SEGMENTS for part in dir_parts)


def _looks_generated(content: str) -> bool:
    head = content[:_GENERATED_SNIFF_CHARS].lower()
    return any(marker in head for marker in _GENERATED_MARKERS)


def _analyze(discovered_file: DiscoveredFile, terms: list[str]) -> tuple[float, str]:
    """Score a single discovered file against `terms`, returning
    (score, reason).
    """
    filename_score = 0.0
    symbol_score = 0.0
    content_score = 0.0
    role_bonus = 0.0
    matched_any = False

    # --- filename / path segment match: highest-weight signal ---
    segments = _path_segments(discovered_file.path)
    filename_terms = [t for t in terms if any(has_word_match(seg, t) for seg in segments)]
    if filename_terms:
        filename_score += WEIGHT_FILENAME * len(filename_terms)
        matched_any = True

    content = ""
    try:
        content = discovered_file.abs_path.read_text(errors="replace")
    except OSError:
        content = ""

    is_asset = _is_asset_like(discovered_file.path, content)

    # --- Python symbol definitions ---
    symbol_names: list[str] = []
    if discovered_file.path.endswith(".py") and content:
        tree = None
        try:
            tree = ast.parse(content)
        except SyntaxError:
            tree = None
        if tree is not None:
            for node in ast.walk(tree):
                if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                    node_matched = False
                    for t in terms:
                        if has_word_match(node.name, t):
                            symbol_score += WEIGHT_SYMBOL
                            matched_any = True
                            node_matched = True
                    if node_matched:
                        symbol_names.append(node.name)

    # --- damped content term frequency ---
    # Skipped for minified/generated/vendored assets (is_asset): a bare
    # word-boundary match there is still not a meaningful "mention" -- the
    # content is not prose or source a developer would read, and a single
    # multi-thousand-character line can otherwise dominate scoring on
    # coincidence alone.
    content_term_counts: dict[str, int] = {}
    if content and not is_asset:
        for t in terms:
            count = count_word_matches(content, t)
            if count > 0:
                content_score += min(CONTENT_CAP, CONTENT_MULT * math.log(1 + count))
                matched_any = True
                content_term_counts[t] = count

    # A large file mentioning a term hundreds of times is not hundreds of
    # times more relevant than a small file mentioning it once -- only the
    # content-frequency component is damped; filename and symbol matches
    # (rarer, more deliberate signals) are unaffected by file size.
    if discovered_file.size > LARGE_FILE_BYTES:
        content_score *= LARGE_FILE_CONTENT_PENALTY

    # --- role bonus ---
    if matched_any and discovered_file.role in ROLE_BONUS_ROLES:
        role_bonus = ROLE_BONUS

    score = filename_score + symbol_score + content_score + role_bonus

    # Bulk data / vendored / build / generated files are down-weighted as a
    # whole, on top of the content-frequency damping above -- a strong
    # filename match inside a data dump is still probably not the file a
    # developer wants opened first.
    if _in_data_path(discovered_file.path):
        score *= DATA_PATH_PENALTY
    if content and _looks_generated(content):
        score *= GENERATED_FILE_PENALTY

    reason = _build_reason(discovered_file.role, filename_terms, symbol_names, content_term_counts)
    return score, reason


def _module_parts(rel_path: str) -> tuple[tuple[str, ...], bool]:
    """Return (dotted-module-parts, is_package_init) for a first-party
    Python file's root-relative path.

    `src/users/session.py` -> (("src", "users", "session"), False)
    `src/users/__init__.py` -> (("src", "users"), True)
    """
    pure = PurePosixPath(rel_path)
    stem = pure.stem
    if stem == "__init__":
        return tuple(pure.parent.parts), True
    return (*pure.parent.parts, stem), False


def _resolve_module_tuple(module_tuple: tuple[str, ...], file_index: set[str]) -> str | None:
    """Resolve a dotted-module-parts tuple to a first-party file path, or
    None if it does not map to any discovered Python file (i.e. it is
    stdlib, third-party, or simply not part of this project).
    """
    if not module_tuple:
        return None
    base = "/".join(module_tuple)
    module_candidate = base + ".py"
    package_candidate = base + "/__init__.py"
    if module_candidate in file_index:
        return module_candidate
    if package_candidate in file_index:
        return package_candidate
    return None


def _imports_of(rel_path: str, content: str, file_index: set[str]) -> set[str]:
    """Parse `content` (the source of `rel_path`) and return the set of
    first-party file paths it imports. Third-party/stdlib imports (those
    that do not resolve to a file under file_index) are silently skipped.
    Files that fail to parse (SyntaxError) yield no imports.
    """
    try:
        tree = ast.parse(content)
    except (SyntaxError, ValueError):
        return set()

    module_parts, is_init = _module_parts(rel_path)
    base_package = list(module_parts) if is_init else list(module_parts[:-1])

    targets: set[str] = set()

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                mod_tuple = tuple(alias.name.split("."))
                resolved = _resolve_module_tuple(mod_tuple, file_index)
                if resolved and resolved != rel_path:
                    targets.add(resolved)

        elif isinstance(node, ast.ImportFrom):
            if node.level and node.level > 0:
                # level 1 ("from . import x" / "from .x import y") means
                # "relative to the current package"; each extra level
                # walks one package up from there.
                up = node.level - 1
                if up > len(base_package):
                    continue
                target_package = base_package[: len(base_package) - up]
            else:
                target_package = []

            if node.module:
                target_prefix = tuple(target_package) + tuple(node.module.split("."))
            else:
                target_prefix = tuple(target_package)

            resolved = _resolve_module_tuple(target_prefix, file_index)
            if resolved and resolved != rel_path:
                targets.add(resolved)

            # The imported name may itself be a submodule rather than an
            # attribute of the resolved module (e.g. "from src.users
            # import session" where session.py is a module) -- try that
            # too.
            for alias in node.names:
                if alias.name == "*":
                    continue
                sub_resolved = _resolve_module_tuple(target_prefix + (alias.name,), file_index)
                if sub_resolved and sub_resolved != rel_path:
                    targets.add(sub_resolved)

    return targets


def _build_import_graph(
    discovered: list[DiscoveredFile],
) -> tuple[dict[str, DiscoveredFile], dict[str, set[str]], dict[str, set[str]]]:
    """Build the first-party Python import graph from `discovered`.

    Returns (py_files, outbound, inbound):
      - py_files: rel path -> DiscoveredFile, for every discovered .py file
      - outbound: rel path -> set of rel paths it imports
      - inbound: rel path -> set of rel paths that import it
    """
    py_files = {f.path: f for f in discovered if f.path.endswith(".py")}
    file_index = set(py_files)

    outbound: dict[str, set[str]] = {}
    for path, discovered_file in py_files.items():
        try:
            content = discovered_file.abs_path.read_text(errors="replace")
        except OSError:
            content = ""
        outbound[path] = _imports_of(path, content, file_index) if content else set()

    inbound: dict[str, set[str]] = {path: set() for path in py_files}
    for source, targets in outbound.items():
        for target in targets:
            inbound.setdefault(target, set()).add(source)

    return py_files, outbound, inbound


def expand_transitively(
    seed_items: list[ContextItem], discovered: list[DiscoveredFile]
) -> tuple[list[ContextItem], int]:
    """Expand `seed_items` across the first-party Python import graph, both
    directions (files a seed imports, and files that import a seed).

    Bounded by MAX_DEPTH hops and MAX_EXPANDED files, with score decayed
    IMPORT_DECAY per hop. Cycle-safe: a `visited` set (seeds plus anything
    already expanded) is checked before a file is ever added as a
    candidate, so a cycle in the import graph simply stops contributing
    new files rather than looping.

    Returns (expanded ContextItems, count of candidates dropped for being
    over MAX_EXPANDED).
    """
    py_files, outbound, inbound = _build_import_graph(discovered)

    seed_paths = {item.path for item in seed_items}
    visited = set(seed_paths)

    # Only .py seeds participate in the import graph.
    frontier: list[tuple[str, float, list[str]]] = [
        (item.path, item.score, []) for item in seed_items if item.path in py_files
    ]

    expanded: dict[str, tuple[float, list[str], str]] = {}
    over_cap_count = 0
    depth = 1

    while depth <= MAX_DEPTH and frontier:
        candidates: dict[str, tuple[float, list[str], str]] = {}

        for path, score, provenance in frontier:
            decayed = score * IMPORT_DECAY
            friendly = PurePosixPath(path).name

            for target in outbound.get(path, ()):
                if target in visited or target in candidates:
                    continue
                edge = f"{path} imports {target}"
                candidates[target] = (decayed, provenance + [edge], f"imported by {friendly}")

            for source in inbound.get(path, ()):
                if source in visited or source in candidates:
                    continue
                edge = f"{source} imports {path}"
                candidates[source] = (decayed, provenance + [edge], f"imports {friendly}")

        if not candidates:
            break

        # Deterministic order: strongest (least-decayed) candidates first,
        # tie-broken on path, so the MAX_EXPANDED cap drops the weakest
        # candidates first rather than arbitrarily.
        ordered = sorted(candidates.items(), key=lambda kv: (-kv[1][0], kv[0]))

        next_frontier: list[tuple[str, float, list[str]]] = []
        for path, (score, provenance, reason) in ordered:
            if len(expanded) >= MAX_EXPANDED:
                over_cap_count += 1
                continue
            expanded[path] = (score, provenance, reason)
            visited.add(path)
            next_frontier.append((path, score, provenance))

        frontier = next_frontier
        depth += 1

    items = [
        ContextItem(
            path=path,
            role=py_files[path].role,
            reason=reason,
            score=score,
            provenance=provenance,
        )
        for path, (score, provenance, reason) in expanded.items()
    ]
    return items, over_cap_count


def _looks_like_secret_key(key: str) -> bool:
    key_lower = _split_camel_and_snake(key.strip()).lower()
    if any(sub in key_lower for sub in _SECRET_KEY_SUBSTRINGS):
        return True
    if "token" in key_lower:
        return not _NON_SECRET_TOKEN_RE.search(key_lower)
    return False


def _redact_line(line: str) -> str:
    """Mask the value on a secret-looking `key: value` / `key = value`
    line, and mask any standalone high-entropy token anywhere in the line
    (e.g. an `sk-...`/`AKIA...` key or a bare base64/hex secret that isn't
    behind a recognizable key at all). Key names and line structure
    survive; only the sensitive-looking value text is replaced.
    """
    match = _SECRET_KEY_LINE_RE.match(line)
    if match and _looks_like_secret_key(match.group("prefix")):
        line = line[: match.start("value")] + REDACTED + line[match.end("value") :]

    for pattern in _ENTROPY_PREFIXED_PATTERNS:
        line = pattern.sub(REDACTED, line)
    line = _ENTROPY_GENERIC_RE.sub(_redact_generic_entropy, line)

    return line


def redact_text(text: str) -> str:
    """Apply `_redact_line` to every line of `text`, preserving line
    count and structure. This is the only place excerpt text is allowed
    to reach a ContextItem without going through redaction first.
    """
    return "\n".join(_redact_line(line) for line in text.splitlines())


def _def_span(node: ast.AST) -> tuple[int, int]:
    """(start_line, end_line), 1-indexed inclusive, for a def/class node,
    capped at MAX_EXCERPT_LINES so a single huge definition cannot blow
    the per-span budget on its own.
    """
    start = node.lineno
    end = getattr(node, "end_lineno", None) or start
    end = min(end, start + MAX_EXCERPT_LINES - 1)
    return start, end


def _matched_symbol_spans(content: str, terms: list[str]) -> list[tuple[int, int]]:
    """Spans for def/class nodes whose name matches a task term -- the
    same signal _analyze() uses to score a file, but here we need the
    actual line range instead of just a boolean/score contribution.
    """
    try:
        tree = ast.parse(content)
    except SyntaxError:
        return []
    spans = []
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            if any(has_word_match(node.name, t) for t in terms):
                spans.append(_def_span(node))
    return spans


def _imported_symbol_spans(content: str, names: set[str]) -> list[tuple[int, int]]:
    """Spans for def/class nodes in `content` whose name is in `names` --
    the definitions actually imported by another file, for import-reached
    items. This is what makes the transitive result usable: session.py's
    excerpt is SessionStore, not an arbitrary head-of-file slice.
    """
    if not names:
        return []
    try:
        tree = ast.parse(content)
    except SyntaxError:
        return []
    spans = []
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            if node.name in names:
                spans.append(_def_span(node))
    return spans


def _matched_line_spans(content: str, terms: list[str]) -> list[tuple[int, int]]:
    """One-line spans for every line containing a task term. This is the
    lowest-priority, "everything else" tier -- used only as a fallback
    when a file has no config-key, doc-heading, or symbol-definition spans
    (see attach_excerpts()), so it does not pull in arbitrary prose lines
    from a file that already has a structural match.
    """
    spans = []
    for lineno, line in enumerate(content.splitlines(), start=1):
        if any(has_word_match(line, t) for t in terms):
            spans.append((lineno, lineno))
    return spans


_CONFIG_KEY_LINE_RE = re.compile(r"^\s*[A-Za-z_][A-Za-z0-9_.\-]*\s*[:=]")


def _config_key_spans(content: str, terms: list[str]) -> list[tuple[int, int]]:
    """One-line spans for `key: value` / `key = value` lines whose key or
    value carries a task term -- the specific config key lines, not
    arbitrary comment prose. Comment lines are skipped even if they
    happen to contain a term (that case falls through to the generic
    fallback tier instead).
    """
    spans = []
    for lineno, line in enumerate(content.splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if not _CONFIG_KEY_LINE_RE.match(stripped):
            continue
        if any(has_word_match(line, t) for t in terms):
            spans.append((lineno, lineno))
    return spans


def _doc_heading_and_assertion_spans(content: str, terms: list[str]) -> list[tuple[int, int]]:
    """One-line spans for a doc heading (`#`/`##`/...) that carries a task
    term, plus every non-blank line under it until the next heading -- the
    assertion lines the heading is introducing. A heading that does not
    match a term contributes nothing, even if a line under it happens to
    mention one (that line is still reachable via the generic fallback
    tier if nothing better exists in the file).
    """
    spans = []
    under_matching_heading = False
    for lineno, line in enumerate(content.splitlines(), start=1):
        stripped = line.lstrip()
        if stripped.startswith("#"):
            if any(has_word_match(line, t) for t in terms):
                spans.append((lineno, lineno))
                under_matching_heading = True
            else:
                under_matching_heading = False
            continue
        if under_matching_heading and stripped:
            spans.append((lineno, lineno))
    return spans


def _merge_and_cap_spans(
    weighted_spans: list[tuple[int, int, float]], line_count: int
) -> list[tuple[int, int, float]]:
    """Merge overlapping/adjacent (start, end, weight) spans, summing the
    weight of whatever merged into each span, then cap each merged span's
    length at MAX_EXCERPT_LINES.
    """
    clipped = [
        (max(1, start), min(line_count, end), weight)
        for start, end, weight in weighted_spans
        if line_count > 0
    ]
    clipped.sort(key=lambda t: (t[0], t[1]))

    merged: list[list] = []
    for start, end, weight in clipped:
        if merged and start <= merged[-1][1] + 1:
            merged[-1][1] = max(merged[-1][1], end)
            merged[-1][2] += weight
        else:
            merged.append([start, end, weight])

    capped = []
    for start, end, weight in merged:
        if end - start + 1 > MAX_EXCERPT_LINES:
            end = start + MAX_EXCERPT_LINES - 1
        capped.append((start, end, weight))
    return capped


def _build_excerpts(content: str, weighted_spans: list[tuple[int, int, float]]) -> list[Excerpt]:
    """Turn weighted candidate spans into the (at most MAX_EXCERPTS_PER_FILE)
    redacted Excerpts for one file: merge, cap span length, keep the
    highest-weight spans up to the per-file cap, then restore reading
    order.
    """
    if not weighted_spans:
        return []
    lines = content.splitlines()
    merged = _merge_and_cap_spans(weighted_spans, len(lines))
    if not merged:
        return []

    merged.sort(key=lambda t: (-t[2], t[0]))
    kept = merged[:MAX_EXCERPTS_PER_FILE]
    kept.sort(key=lambda t: t[0])

    excerpts = []
    for start, end, _weight in kept:
        span_text = "\n".join(lines[start - 1 : end])
        span_text = _truncate_chars(span_text)
        excerpts.append(Excerpt(start_line=start, end_line=end, text=redact_text(span_text)))
    return excerpts


def _truncate_chars(text: str) -> str:
    """Cap `text` at MAX_EXCERPT_CHARS, appending TRUNCATION_MARKER when
    truncation happened. This is what MAX_EXCERPT_LINES cannot provide on
    its own: a single very long line (e.g. one 4,000-character minified
    line) is still bounded, because the cap is on character count, not
    line count.
    """
    if len(text) <= MAX_EXCERPT_CHARS:
        return text
    return text[:MAX_EXCERPT_CHARS].rstrip() + TRUNCATION_MARKER


def _imported_names_of(rel_path: str, content: str, file_index: set[str]) -> dict[str, set[str]]:
    """Like _imports_of, but returns target path -> the specific names
    imported from it via `from target import name[, ...]`. Plain `import
    module` statements bring no specific names and are not represented
    here -- they carry no excerpt-worthy symbol list.
    """
    try:
        tree = ast.parse(content)
    except (SyntaxError, ValueError):
        return {}

    module_parts, is_init = _module_parts(rel_path)
    base_package = list(module_parts) if is_init else list(module_parts[:-1])

    result: dict[str, set[str]] = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.ImportFrom):
            continue

        if node.level and node.level > 0:
            up = node.level - 1
            if up > len(base_package):
                continue
            target_package = base_package[: len(base_package) - up]
        else:
            target_package = []

        if node.module:
            target_prefix = tuple(target_package) + tuple(node.module.split("."))
        else:
            target_prefix = tuple(target_package)

        resolved = _resolve_module_tuple(target_prefix, file_index)
        if not resolved or resolved == rel_path:
            continue

        names = {alias.name for alias in node.names if alias.name != "*"}
        if names:
            result.setdefault(resolved, set()).update(names)

    return result


def _build_import_name_graph(discovered: list[DiscoveredFile]) -> dict[str, dict[str, set[str]]]:
    """rel path -> {target rel path -> names imported from it}, for every
    discovered first-party Python file.
    """
    py_files = {f.path: f for f in discovered if f.path.endswith(".py")}
    file_index = set(py_files)

    graph: dict[str, dict[str, set[str]]] = {}
    for path, discovered_file in py_files.items():
        try:
            content = discovered_file.abs_path.read_text(errors="replace")
        except OSError:
            content = ""
        graph[path] = _imported_names_of(path, content, file_index) if content else {}
    return graph


def _importer_of(item_path: str, provenance: list[str]) -> str | None:
    """If `item_path` was reached because some other file in `provenance`
    imports it (i.e. this item is the *imported* file, not the importer),
    return that other file's path. Provenance edges are recorded as
    "<importer> imports <importee>" strings by expand_transitively().
    """
    for edge in reversed(provenance):
        if " imports " not in edge:
            continue
        importer, _, importee = edge.partition(" imports ")
        if importee == item_path:
            return importer
    return None


def attach_excerpts(
    items: list[ContextItem], discovered: list[DiscoveredFile], task: str
) -> int:
    """Populate `item.excerpts` on every item with the bounded, redacted
    spans that justified its inclusion, then enforce the package-wide
    MAX_PACKAGE_BYTES budget across all items, dropping the lowest-scored
    items' excerpts first.

    Returns the number of excerpts dropped for being over the package
    budget (for trace["excerpts_dropped_over_budget"]).
    """
    terms = tokenize(task)
    discovered_index = {f.path: f for f in discovered}
    import_name_graph = _build_import_name_graph(discovered)

    for item in items:
        discovered_file = discovered_index.get(item.path)
        if discovered_file is None:
            continue
        try:
            content = discovered_file.abs_path.read_text(errors="replace")
        except OSError:
            content = ""
        if not content:
            continue

        # Structural spans, highest priority first: the definitions
        # actually imported (import-reached files), matched symbol
        # definitions, config key lines, doc headings and their assertion
        # lines. A bare content-frequency line (the "everything else"
        # tier) is only used as a fallback when a file has none of these
        # -- otherwise it pads out excerpts with arbitrary prose that
        # happens to contain a term (the middleware.py docstring-sentence
        # problem this step fixes).
        structural_spans: list[tuple[int, int, float]] = []

        if item.path.endswith(".py"):
            importer = _importer_of(item.path, item.provenance)
            if importer:
                imported_names = import_name_graph.get(importer, {}).get(item.path, set())
                for start, end in _imported_symbol_spans(content, imported_names):
                    structural_spans.append((start, end, WEIGHT_IMPORTED_SYMBOL))

            for start, end in _matched_symbol_spans(content, terms):
                structural_spans.append((start, end, WEIGHT_MATCHED_SYMBOL))

        if discovered_file.role == "config":
            for start, end in _config_key_spans(content, terms):
                structural_spans.append((start, end, WEIGHT_CONFIG_KEY))

        if discovered_file.role == "docs":
            for start, end in _doc_heading_and_assertion_spans(content, terms):
                structural_spans.append((start, end, WEIGHT_DOC_ASSERTION))

        if structural_spans:
            weighted_spans = structural_spans
        elif _is_asset_like(discovered_file.path, content):
            # No structural spans (no imported/matched symbol, config key,
            # or doc heading) and the file itself is a minified/generated
            # asset -- the generic content-line fallback would otherwise
            # dump an arbitrary slice of a minified line as if it were
            # prose worth reading. Such an item (reached only via a
            # filename/path match) gets no excerpt rather than a
            # meaningless one.
            weighted_spans = []
        else:
            weighted_spans = [
                (start, end, WEIGHT_MATCHED_LINE)
                for start, end in _matched_line_spans(content, terms)
            ]

        item.excerpts = _build_excerpts(content, weighted_spans)

    return _enforce_package_excerpt_budget(items)


def _enforce_package_excerpt_budget(items: list[ContextItem]) -> int:
    """If total excerpt bytes across `items` exceeds MAX_PACKAGE_BYTES,
    drop whole excerpts -- lowest item score first -- until it does not.
    Returns the number of excerpts dropped.
    """
    entries: list[tuple[ContextItem, Excerpt, int]] = []
    total = 0
    for item in items:
        for excerpt in item.excerpts:
            size = len(excerpt.text.encode("utf-8"))
            entries.append((item, excerpt, size))
            total += size

    if total <= MAX_PACKAGE_BYTES:
        return 0

    # Ascending by item score (lowest first); deterministic tie-break.
    entries.sort(key=lambda entry: (entry[0].score, entry[0].path, entry[1].start_line))

    to_drop_ids: set[int] = set()
    remaining = total
    for item, excerpt, size in entries:
        if remaining <= MAX_PACKAGE_BYTES:
            break
        to_drop_ids.add(id(excerpt))
        remaining -= size

    for item in items:
        item.excerpts = [e for e in item.excerpts if id(e) not in to_drop_ids]

    return len(to_drop_ids)


def score_file(discovered_file: DiscoveredFile, terms: list[str]) -> float:
    """Score `discovered_file` against `terms`. See module docstring for
    the weighting scheme.
    """
    score, _reasons = _analyze(discovered_file, terms)
    return score


def select(
    discovered: list[DiscoveredFile], task: str
) -> tuple[list[ContextItem], dict[str, int]]:
    """Tokenize `task`, score every discovered file, and return
    (ranked ContextItems above threshold and within the cap,
    extra exclusion-reason counts for "below_threshold" and "over_cap").
    """
    terms = tokenize(task)

    scored: list[tuple[float, DiscoveredFile, str]] = []
    for discovered_file in discovered:
        score, reason = _analyze(discovered_file, terms)
        scored.append((score, discovered_file, reason))

    above = [s for s in scored if s[0] > SCORE_THRESHOLD]
    below_count = len(scored) - len(above)

    # Stable rank: score descending, tie-break on path ascending for
    # determinism.
    above.sort(key=lambda s: (-s[0], s[1].path))

    kept = above[:MAX_SEEDS]
    seed_over_cap_count = len(above) - len(kept)

    seed_items = [
        ContextItem(
            path=discovered_file.path,
            role=discovered_file.role,
            reason=reason,
            score=score,
        )
        for score, discovered_file, reason in kept
    ]

    expanded_items, expansion_over_cap_count = expand_transitively(seed_items, discovered)

    # Merge seeds and expanded items into a single ranking -- score
    # descending across both groups, tie-broken on path -- rather than
    # appending expanded items after seeds regardless of score.
    combined = seed_items + expanded_items
    combined.sort(key=lambda item: (-item.score, item.path))

    final_items = combined[:MAX_INCLUDED]
    final_over_cap_count = len(combined) - len(final_items)

    extra_exclusions = {
        "below_threshold": below_count,
        "over_cap": seed_over_cap_count + expansion_over_cap_count + final_over_cap_count,
    }
    return final_items, extra_exclusions
